### ISSUE TITLE
stitch doesn't work on single channel images

### ISSUE THREAD

**Issue by jimfinnis** [AU-ExoMars/PCOT#63]
I think it thinks they are [h,w,1] and not [h,w].
```
Traceback (most recent call last):
  File "C:\Users\Jim\PCOT\src\pcot\xform.py", line 864, in perform
    self.type.uichange(self)
  File "C:\Users\Jim\PCOT\src\pcot\xforms\xformstitch.py", line 143, in uichange
    self.perform(node)
  File "C:\Users\Jim\PCOT\src\pcot\xforms\xformstitch.py", line 123, in perform
    raise e
  File "C:\Users\Jim\PCOT\src\pcot\xforms\xformstitch.py", line 112, in perform
    img[y:y + srcimg.h, x:x + srcimg.w] = srcimg.img
ValueError: could not broadcast input array from shape (16,16) into shape (16,16,1)
```

**Comment by jimfinnis** [comment]
Fixed - I was generating the output image as (h,w,n) even if there was only one band in the inputs - should be (h,w) in that case.
